### ISSUE TITLE
xcode 7 - swift 2 problems

### ISSUE THREAD

**Issue by johndpope** [FabrizioBrancati/BFKit-Swift#1]
![screen shot 2015-06-30 at 2 52 38 pm](https://cloud.githubusercontent.com/assets/289994/8424076/ab6840f0-1f37-11e5-8490-13606c35e644.png)

**Comment by FabrizioBrancati** [comment]
In Swift 2 the `do-while` is now `repeat-while`

**Comment by FabrizioBrancati** [comment]
Thanks! :+1:
