### ISSUE TITLE
about SCREEN_WIDTH in UIDevice+BFKit.swift

### ISSUE THREAD

**Issue by jiongge** [FabrizioBrancati/BFKit-Swift#2]
UIScreen.mainScreen().bounds.size is same regardless of the direction of mobile phone before iOS_7_1 ,but it's changed after  iOS_7_1

for example:
////////////////////////
func getFixedScreenSize()->CGSize{
        let screenSize=UIScreen.mainScreen().bounds.size
        if((NSFoundationVersionNumber <= NSFoundationVersionNumber_iOS_7_1)&&UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication().statusBarOrientation)){
            return CGSizeMake(screenSize.height, screenSize.width)
        }
        return screenSize
    }

**Comment by FabrizioBrancati** [comment]
Thanks, I've made some tests and seem that your solution works!
I'll implement it in the next version.
