### ISSUE TITLE
Extension Array - method random() does never select last element

### ISSUE THREAD

**Issue by on123** [FabrizioBrancati/BFKit-Swift#26]
Hi,

I think the function "random()" in the array extension does only return a random element besides the last one.

The function `randomInt(range: ClosedRange<Int>) -> Int` which is used, never returns the upperBound of the range, but only the upperBound -1.

e.g.
```
var myArray = ["One","Two","Three"]
for i in 1...100 {
    print(myArray.random())
}
```

will never print "Three".

```
for i in 1...100 {
    print("\(randomInt(range: 0...1))")
}
```

will never print "1"

Should be easy to fix :-)

Oliver

**Comment by FabrizioBrancati** [comment]
Thank you! 👍

**Comment by FabrizioBrancati** [comment]
I've fixed it and I also have rewritten the test to check that every number is generated

**Comment by on123** [comment]
Wow - super fast response and fix 👍
Thank you for sharing your code!
