### ISSUE TITLE
FileManagerExtension.swift  mainBundlePath() return nil

### ISSUE THREAD

**Issue by jiongge** [FabrizioBrancati/BFKit-Swift#27]
// MARK: - Functions
    
    /// Get the path for a PathType.
    ///
    /// - Parameter path: Path type.
    /// - Returns: Returns the path type String.
    public func pathFor(_ path: PathType) -> String? {
        var pathString: String?
        
        switch path {
        case .mainBundle:
            pathString = self.mainBundlePath()
       ...
        }
        
        return pathString
    }

self.mainBundlePath() always return nil

I recommend to switch  

   /// Get Main Bundle path for a filename.
    ///
    /// - Parameter file: Filename
    /// - Returns: Returns the path as a String.
    public func mainBundlePath(file: String = "") -> String? {
        return file.isEmpty ? Bundle.main.bundlePath : Bundle.main.path(forResource: file.deletingPathExtension, ofType: file.pathExtension)
    }

**Comment by FabrizioBrancati** [comment]
Thanks! I've changed it 👍
