### ISSUE TITLE
Documentation issue warnings

### ISSUE THREAD

**Issue by TripwireNL** [FabrizioBrancati/BFKit-Swift#31]
Hi,

I keep getting allot of warnings about Documentation issues when building my project. They all are about parameters which are not found in the function declaration. Like this one:
/Pods/BFKit/Source/BFKit/BFCryptor.h:118:12: Parameter 'data' not found in the function declaration
/Pods/BFKit/Source/BFKit/BFCryptor.m:29:9: In file included from /Pods/BFKit/Source/BFKit/BFCryptor.m:29:

It's not really a bug but I like my projects warning free :) 

Thx!

**Comment by TripwireNL** [comment]
Ha nvm was using BFKit instead of using BFKit-swift :)

**Comment by FabrizioBrancati** [comment]
Are we talking about [NVM](https://github.com/creationix/nvm)?

**Comment by TripwireNL** [comment]
No I meant never mind :)
