### ISSUE TITLE
BFTextField - Clear Button

### ISSUE THREAD

**Issue by wdcurry** [FabrizioBrancati/BFKit-Swift#32]
.. doesn't seem to work when set to always be visible.. a minor fyi ;)

A most impressive repo!

**Comment by FabrizioBrancati** [comment]
Thanks! 👍 
There was a bug on BFTextField with or without the clear button

**Comment by FabrizioBrancati** [comment]
Turns out there was a bug on the `substring` function, thanks! 👍
