### ISSUE TITLE
BFTouchID error after ios10.0

### ISSUE THREAD

**Issue by AbooJan** [FabrizioBrancati/BFKit-Swift#34]
after iOS 10.0，when I call `showTouchID` function, it will callback `systemCancel` error first。

I set the breakpoint and see the error. when call `context.evaluatePolicy` , system will show the touchID alert, and then this function will callback `systemCancel` error first. After I auth the touchID, it callback success.

this error can not see in ios 9.0 。

some one know why

**Comment by FabrizioBrancati** [comment]
I'm sorry but I can't reproduce your bug.
Everything works fine on my iPhone X, even with Face ID.
Can you give me more details?

**Comment by AbooJan** [comment]
My device is iPhone 7. iOS 11.1.2

here is the step:
1. call `showTouchID ` function
2. app show the touchID alert
3. function callback `systemCancel` error
4. My finger touch iPhone to verify touchID
5. function callback `success` result

you will see the `showTouchID ` function callback twice. 
but my expectation is callback once

**Comment by FabrizioBrancati** [comment]
I made a complete rewrite of the biometric auth with a new Struct `BFBiometric`.
Can you try the `feature/biometric` branch, please?

**Comment by AbooJan** [comment]
OK, it work, thanks!
