### ISSUE TITLE
UIView @IBDesignable/@IBInspectable can't show in storyboard

### ISSUE THREAD

**Issue by weixianlove** [FabrizioBrancati/BFKit-Swift#37]
I see in BFKit has a UIView extension that used IBDesignable/IBInspectable, But it's can't show in the storyboard。And now I only can use A empty custom view to inherit UIView and in storyboard select the customView。I want now if there any other way to do that

**Comment by FabrizioBrancati** [comment]
How did you include BFKit-Swift?
Source Code, CocoaPods or Carthage?

**Comment by FabrizioBrancati** [comment]
Hi, news on that?

**Comment by weixianlove** [comment]
it's ok now,thanks
