### ISSUE TITLE
What's happened?

### ISSUE THREAD

**Issue by IUyuRtBbyQnRCI** [FabrizioBrancati/BFKit-Swift#40]
<img width="529" alt="wx20180816-142810 2x" src="https://user-images.githubusercontent.com/14257778/44192128-d8247380-a160-11e8-94fc-210ed4a06df8.png">
not be installed

**Comment by FabrizioBrancati** [comment]
I think that you found that URL [here](https://github.fabriziobrancati.com/documentation/BFKit-Swift/), right?
It’s wrong, I have to change it and maybe to update that documentation, sorry for the incovenience, I will fix it in a couple of days, thanks! 😄

**Comment by FabrizioBrancati** [comment]
It's now fixed and it's even better!
Thanks
