### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by giordanocardillo** [FabrizioBrancati/BFKit-Swift#46]
Hello, I'm having problems on my project using this library. I've found this StackOverflow article, is this flag already in the build process for the library?

BUILD_LIBRARY_FOR_DISTRIBUTION

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

**Comment by FabrizioBrancati** [comment]
Hi @giordanocardillo, I've just enabled the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag on the framework project, you can find it on the `develop` branch.

How are you integrating the framework?
Because BFKit-Swift is open-source and you can build it by yourself, without errors about the Swift version.

**Comment by giordanocardillo** [comment]
Hi, I’m using it with cocoapods

**Comment by FabrizioBrancati** [comment]
If you're using CocoaPods an error like this is strange. Did you try to clean and build again?

**Comment by FabrizioBrancati** [comment]
Hi @giordanocardillo, news about this issue? 😄

**Comment by FabrizioBrancati** [comment]
Hi @giordanocardillo, I will close this issue due to inactivity, feel free to reopen if you still encounter this error
